# Generated by Django 5.1.6 on 2025-04-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('HOLIDAY', 'Holiday'), ('EXAM', 'Examination'), ('SPORTS', 'Sports Day'), ('MEETING', 'Meeting'), ('ACTIVITY', 'Activity'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
