# Generated by Django 5.1.6 on 2025-04-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_on_website',
            field=models.BooleanField(default=False, help_text='If checked, this event will also be displayed on the public website'),
        ),
    ]
