# Generated by Django 5.1.6 on 2025-03-06 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header_text', models.CharField(default='Admission Letter', max_length=255)),
                ('body_template', models.TextField(help_text='Use placeholders like {student_name}, {grade}, etc.')),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signatory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('signatory_position', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Letter Template',
                'verbose_name_plural': 'Admission Letter Templates',
            },
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('ADMIN', 'Admin')], max_length=10)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='id_card_templates/')),
                ('header_text', models.CharField(default='School ID Card', max_length=255)),
                ('card_width', models.PositiveIntegerField(default=1000)),
                ('card_height', models.PositiveIntegerField(default=600)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ID Card Template',
                'verbose_name_plural': 'ID Card Templates',
            },
        ),
        migrations.CreateModel(
            name='AdmissionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('admission_date', models.DateField()),
                ('academic_year', models.CharField(max_length=20)),
                ('grade_admitted', models.CharField(max_length=20)),
                ('section_admitted', models.CharField(blank=True, max_length=20, null=True)),
                ('fee_details', models.TextField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_letters', to='users.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admissionlettertemplate')),
            ],
            options={
                'verbose_name': 'Admission Letter',
                'verbose_name_plural': 'Admission Letters',
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('barcode_data', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.idcardtemplate')),
            ],
            options={
                'verbose_name': 'ID Card',
                'verbose_name_plural': 'ID Cards',
            },
        ),
    ]
