# Generated by Django 5.1.6 on 2025-03-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admissionlettertemplate_idcardtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='notify_assignments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='notify_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='notify_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='notify_grades',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#4e73df', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='principal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
