# Generated by Django 5.1.6 on 2025-03-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_default_email_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
