# Generated by Django 5.1.6 on 2025-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
