# Generated by Django 5.1.6 on 2025-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_student_grade_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='footer_color',
            field=models.CharField(default='#f8f9fc', max_length=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='header_color',
            field=models.CharField(default='#4e73df', max_length=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='use_curved_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='card_height',
            field=models.PositiveIntegerField(default=638),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='card_width',
            field=models.PositiveIntegerField(default=1013),
        ),
    ]
