# Generated by Django 5.1.6 on 2025-03-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_idcardtemplate_footer_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Custom text for card footer. Use {school_name}, {school_address}, {school_phone} as placeholders.', null=True),
        ),
    ]
