# Generated by Django 5.1.6 on 2025-03-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_schoolsettings_enable_messaging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_repeating',
            field=models.BooleanField(default=False, help_text='If True, student will repeat the current grade in the next academic year'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_promoted_date',
            field=models.DateField(blank=True, help_text='Date when student was last promoted to a new grade', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', help_text='Current enrollment status of the student', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='years_in_current_grade',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of years student has spent in the current grade'),
        ),
    ]
