# Generated by Django 5.1.6 on 2025-04-10 23:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_status_to_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('ACCOUNTANT', 'Accountant'), ('SECRETARY', 'Secretary'), ('RECEPTIONIST', 'Receptionist'), ('SECURITY', 'Security'), ('JANITOR', 'Janitor'), ('COOK', 'Cook'), ('CLEANER', 'Cleaner'), ('STAFF', 'Other Staff')], default='STUDENT', max_length=15),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('staff_type', models.CharField(choices=[('ADMINISTRATIVE', 'Administrative'), ('SUPPORT', 'Support'), ('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Security'), ('FOOD_SERVICE', 'Food Service'), ('OTHER', 'Other')], default='ADMINISTRATIVE', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.staffmember')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
            },
        ),
    ]
