# Generated by Django 5.1.6 on 2025-06-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_role_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='background_check',
            field=models.FileField(blank=True, help_text='Upload background check documents (PDF)', null=True, upload_to='staff_documents/background_checks/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='certificates',
            field=models.FileField(blank=True, help_text='Upload relevant certificates (PDF, JPG, PNG)', null=True, upload_to='staff_documents/certificates/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='contract_documents',
            field=models.FileField(blank=True, help_text='Upload contract documents (PDF)', null=True, upload_to='staff_documents/contracts/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='documents_notes',
            field=models.TextField(blank=True, help_text='Additional notes about uploaded documents', null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='job_application',
            field=models.FileField(blank=True, help_text='Upload job application (PDF, DOC, DOCX)', null=True, upload_to='staff_documents/applications/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='other_documents',
            field=models.FileField(blank=True, help_text='Upload other relevant documents (PDF, JPG, PNG)', null=True, upload_to='staff_documents/other/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='references',
            field=models.FileField(blank=True, help_text='Upload reference letters (PDF, DOC, DOCX)', null=True, upload_to='staff_documents/references/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='resume_cv',
            field=models.FileField(blank=True, help_text='Upload resume/CV (PDF, DOC, DOCX)', null=True, upload_to='staff_documents/resumes/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='training_records',
            field=models.FileField(blank=True, help_text='Upload training records (PDF, JPG, PNG)', null=True, upload_to='staff_documents/training/'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, help_text='Upload birth certificate (PDF, JPG, PNG)', null=True, upload_to='student_documents/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='documents_notes',
            field=models.TextField(blank=True, help_text='Additional notes about uploaded documents', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_form',
            field=models.FileField(blank=True, help_text='Upload emergency contact form (PDF, JPG, PNG)', null=True, upload_to='student_documents/emergency_contacts/'),
        ),
        migrations.AddField(
            model_name='student',
            name='immunization_records',
            field=models.FileField(blank=True, help_text='Upload immunization records (PDF, JPG, PNG)', null=True, upload_to='student_documents/immunization/'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_records',
            field=models.FileField(blank=True, help_text='Upload medical records (PDF, JPG, PNG)', null=True, upload_to='student_documents/medical_records/'),
        ),
        migrations.AddField(
            model_name='student',
            name='other_documents',
            field=models.FileField(blank=True, help_text='Upload other relevant documents (PDF, JPG, PNG)', null=True, upload_to='student_documents/other/'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_records',
            field=models.FileField(blank=True, help_text='Upload previous school records (PDF, JPG, PNG)', null=True, upload_to='student_documents/school_records/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='background_check',
            field=models.FileField(blank=True, help_text='Upload background check documents (PDF)', null=True, upload_to='teacher_documents/background_checks/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_certificates',
            field=models.FileField(blank=True, help_text='Upload degree certificates (PDF, JPG, PNG)', null=True, upload_to='teacher_documents/degrees/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='documents_notes',
            field=models.TextField(blank=True, help_text='Additional notes about uploaded documents', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='other_documents',
            field=models.FileField(blank=True, help_text='Upload other relevant documents (PDF, JPG, PNG)', null=True, upload_to='teacher_documents/other/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='professional_development',
            field=models.FileField(blank=True, help_text='Upload professional development certificates (PDF, JPG, PNG)', null=True, upload_to='teacher_documents/professional_dev/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='references',
            field=models.FileField(blank=True, help_text='Upload reference letters (PDF, DOC, DOCX)', null=True, upload_to='teacher_documents/references/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='resume_cv',
            field=models.FileField(blank=True, help_text='Upload resume/CV (PDF, DOC, DOCX)', null=True, upload_to='teacher_documents/resumes/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_certificate',
            field=models.FileField(blank=True, help_text='Upload teaching certificate (PDF, JPG, PNG)', null=True, upload_to='teacher_documents/certificates/'),
        ),
    ]
