# Generated by Django 5.1.6 on 2025-06-13 07:03

import website.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_staffmember_background_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionlettertemplate',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.get_cloudinary_storage, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=website.storage.get_cloudinary_storage, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.get_cloudinary_storage, upload_to='id_card_templates/'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=website.storage.get_cloudinary_storage, upload_to='school_logo/'),
        ),
    ]
