# Generated by Django 5.1.6 on 2025-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_recreate_schoolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='allowed_file_types',
            field=models.CharField(default='pdf,doc,docx,txt,jpg,jpeg,png,gif', help_text='Comma-separated list of allowed file extensions (without dots)', max_length=500),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='auto_delete_messages_days',
            field=models.PositiveIntegerField(default=60, help_text='Auto-delete messages after X days (0 = never delete)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='max_concurrent_users',
            field=models.PositiveIntegerField(default=100, help_text='Maximum simultaneous chat users (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=2, help_text='Maximum file size in MB for attachments'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='max_messages_per_day',
            field=models.PositiveIntegerField(default=50, help_text='Maximum messages a user can send per day (0 = unlimited)'),
        ),
    ]
