# Generated by Django 5.1.6 on 2025-08-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_schoolsettings_allowed_file_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_visitor_thank_you_emails',
            field=models.BooleanField(default=True, help_text='Enable automatic thank you emails for visitors on checkout'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='visitor_thank_you_email_template',
            field=models.TextField(blank=True, default='Dear {visitor_name},\n\nThank you for visiting {school_name} today. We appreciate your time and hope you had a pleasant experience.\n\nBest regards,\n{school_name} Team', help_text='Default template for visitor thank you emails. Use {visitor_name}, {school_name}, {visit_date} as placeholders.', null=True),
        ),
    ]
