# Generated by Django 5.1.6 on 2025-08-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_schoolsettings_enable_visitor_thank_you_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='student_email_domain',
            field=models.CharField(blank=True, help_text='Domain used for auto-generated student emails (e.g., deigratiams.edu.gh). Leave blank to use default.', max_length=255, null=True),
        ),
    ]
