# fly.toml app configuration file generated for school-management-system
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "school-management-system"
primary_region = "iad"

[build]

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "ricas_school_manager.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health/"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"
