# fly.toml app configuration file generated for deigratia-school on 2025-06-09T19:37:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deigratia-school'
primary_region = 'lhr'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput && python manage.py setup_production --skip-static'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/staticfiles'
  url_prefix = '/static/'

# Media files handled by Cloudinary CDN (no local storage needed)
# This reduces costs and improves performance
