# Generated by Django 5.1.2 on 2024-10-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_admissionsinquiry_contactmessage_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='tour_locations/')),
                ('video_url', models.URLField(blank=True, help_text='URL to a video tour (e.g., YouTube)')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['staff_type', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='staff',
            name='executive_position',
            field=models.CharField(blank=True, choices=[('director', 'School Director'), ('headteacher', 'Head Teacher'), ('administrator', 'Administrator'), ('supervisor', 'Supervisor'), ('coordinator', 'Coordinator'), ('other', 'Other Executive')], help_text='Only applicable for Executive Staff', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('executive', 'Executive Staff'), ('teaching', 'Teaching Staff'), ('support', 'Support Staff')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.tourlocation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
