# Generated by Django 5.1.2 on 2024-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tourlocation_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
