# Generated by Django 5.1.2 on 2024-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_heroslide_remove_homepagesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_logo', models.ImageField(help_text='Main school logo displayed in the header', upload_to='site/')),
                ('footer_logo', models.ImageField(blank=True, help_text='Optional different logo for footer', null=True, upload_to='site/')),
                ('contact_email', models.EmailField(help_text='Main contact email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Main contact phone number', max_length=20)),
                ('address', models.TextField(help_text="School's physical address")),
                ('office_hours', models.CharField(default='Mon-Fri: 8:00 AM - 4:00 PM', help_text='Office hours', max_length=100)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
