# Generated by Django 5.1.2 on 2024-10-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us'), ('academics', 'Academics'), ('admissions', 'Admissions'), ('events', 'Events'), ('news', 'News'), ('contact', 'Contact')], max_length=20)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us'), ('academics', 'Academics'), ('admissions', 'Admissions')], max_length=20)),
                ('section', models.CharField(choices=[('hero', 'Hero Section'), ('about_preview', 'About Preview'), ('featured_programs', 'Featured Programs'), ('why_choose_us', 'Why Choose Us'), ('mission', 'Mission Statement'), ('vision', 'Vision Statement'), ('history', 'Our History'), ('values', 'Our Values'), ('curriculum_overview', 'Curriculum Overview'), ('teaching_method', 'Teaching Method'), ('programs', 'Programs'), ('facilities', 'Facilities'), ('admission_process', 'Admission Process'), ('requirements', 'Requirements'), ('fees', 'Fees and Tuition'), ('scholarships', 'Scholarships')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_content/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ['page', 'order'],
                'unique_together': {('page', 'section')},
            },
        ),
        migrations.DeleteModel(
            name='HomePageSettings',
        ),
    ]
