# Generated by Django 5.1.2 on 2024-10-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_faq_pagecontent_delete_homepagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='achievements',
            field=models.TextField(blank=True, help_text='Notable achievements and contributions'),
        ),
        migrations.AddField(
            model_name='staff',
            name='interests',
            field=models.TextField(blank=True, help_text='Professional interests and specializations'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured staff will be shown on the home and about pages'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.TextField(blank=True, help_text='Academic and professional qualifications'),
        ),
    ]
