# Generated by Django 5.1.6 on 2025-04-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_staff_achievements_staff_interests_staff_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontessoriMethodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('child', 'Child (Child-Centered Learning)'), ('hands-helping', 'Hands Helping (Prepared Environment)'), ('brain', 'Brain (Hands-on Learning)'), ('users', 'Users (Mixed-Age Groups)'), ('star', 'Star'), ('heart', 'Heart'), ('lightbulb', 'Lightbulb'), ('book', 'Book'), ('graduation-cap', 'Graduation Cap'), ('seedling', 'Seedling')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Montessori Method Item',
                'verbose_name_plural': 'Montessori Method Items',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('about_preview', 'About Preview'), ('featured_programs', 'Featured Programs'), ('why_choose_us', 'Why Choose Us'), ('about_hero', 'About Hero Section'), ('mission', 'Mission Statement'), ('vision', 'Vision Statement'), ('story', 'Our Story'), ('montessori_method', 'Montessori Method'), ('values', 'Our Values'), ('curriculum_overview', 'Curriculum Overview'), ('teaching_method', 'Teaching Method'), ('programs', 'Programs'), ('facilities', 'Facilities'), ('admission_process', 'Admission Process'), ('requirements', 'Requirements'), ('fees', 'Fees and Tuition'), ('scholarships', 'Scholarships')], max_length=50),
        ),
    ]
