# Generated by Django 5.1.6 on 2025-04-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_montessorimethoditem_alter_pagecontent_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(help_text='Main content text for this section'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, help_text="Image for this section. For 'Our Story' section, this will be the main image shown beside the text.", null=True, upload_to='page_content/'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this section appears on the page'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(help_text='Title for this section', max_length=200),
        ),
    ]
