# Generated by Django 5.1.6 on 2025-04-06 09:23

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_pagecontent_content_alter_pagecontent_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('toddler', 'Toddler Program'), ('primary', 'Primary Program'), ('elementary', 'Elementary Program')], max_length=20)),
                ('age_range', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='academics/programs/')),
                ('features', models.JSONField(default=list, help_text='List of program features')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academic Program',
                'verbose_name_plural': 'Academic Programs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('clipboard-check', 'Observation'), ('comments', 'Communication'), ('book-reader', 'Portfolio'), ('chart-line', 'Progress')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assessment Method',
                'verbose_name_plural': 'Assessment Methods',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curriculum Approach Item',
                'verbose_name_plural': 'Curriculum Approach Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('music', 'Music'), ('palette', 'Art'), ('seedling', 'Garden'), ('globe', 'Cultural'), ('microscope', 'Science'), ('book', 'Language'), ('robot', 'Technology'), ('heart', 'Social-Emotional')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Special Program',
                'verbose_name_plural': 'Special Programs',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for this section.', null=True, upload_to=website.models.PageContent.get_upload_path),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('about_preview', 'About Preview'), ('featured_programs', 'Featured Programs'), ('why_choose_us', 'Why Choose Us'), ('about_hero', 'About Hero Section'), ('mission', 'Mission Statement'), ('vision', 'Vision Statement'), ('story', 'Our Story'), ('montessori_method', 'Montessori Method'), ('values', 'Our Values'), ('academics_hero', 'Academics Hero Section'), ('curriculum_image', 'Curriculum Approach Image'), ('assessment_intro', 'Assessment Introduction'), ('cta_section', 'Call to Action Section'), ('admission_process', 'Admission Process'), ('requirements', 'Requirements'), ('fees', 'Fees and Tuition'), ('scholarships', 'Scholarships')], max_length=50),
        ),
    ]
