# Generated by Django 5.1.6 on 2025-04-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_academicprogram_assessmentmethod_curriculumapproach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Hero Section'), ('newsletter', 'Newsletter Section'), ('cta', 'Call to Action Section')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='events/sections/')),
                ('content', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=200)),
                ('additional_button_text', models.CharField(blank=True, max_length=50)),
                ('additional_button_link', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Page Section',
                'verbose_name_plural': 'Event Page Sections',
            },
        ),
        migrations.CreateModel(
            name='PastEventHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/highlights/')),
                ('date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='website.eventcategory'),
        ),
    ]
