# Generated by Django 5.1.6 on 2025-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_eventcategory_eventpagecontent_pasteventhighlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpagecontent',
            name='calendar_placeholder_image',
            field=models.ImageField(blank=True, help_text='Placeholder image for the calendar widget', null=True, upload_to='events/sections/'),
        ),
    ]
