# Generated by Django 5.1.6 on 2025-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_gallery_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
