# Generated by Django 5.1.6 on 2025-04-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_gallery_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
