# Generated by Django 5.1.6 on 2025-04-15 23:06

from django.db import migrations
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_announcementcategory_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.RunPython(code=lambda apps, schema_editor: populate_announcement_slugs(apps, schema_editor)),
    ]

def populate_announcement_slugs(apps, schema_editor):
    # Get the historical model
    Announcement = apps.get_model('website', 'Announcement')

    # Loop through all announcements
    for announcement in Announcement.objects.all():
        # Skip if already has a slug
        if announcement.slug:
            continue

        # Create a base slug from the title
        base_slug = slugify(announcement.title)

        # Make sure the slug is unique
        slug = base_slug
        counter = 1

        # Keep checking until we find a unique slug
        while Announcement.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        # Set the slug and save
        announcement.slug = slug
        announcement.save()
