# Generated by Django 5.1.6 on 2025-04-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_populate_announcement_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
