# Generated by Django 5.1.6 on 2025-04-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_make_slug_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us'), ('academics', 'Academics'), ('admissions', 'Admissions'), ('events', 'Events'), ('news', 'News & Announcements')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('about_preview', 'About Preview'), ('featured_programs', 'Featured Programs'), ('why_choose_us', 'Why Choose Us'), ('about_hero', 'About Hero Section'), ('mission', 'Mission Statement'), ('vision', 'Vision Statement'), ('story', 'Our Story'), ('montessori_method', 'Montessori Method'), ('values', 'Our Values'), ('academics_hero', 'Academics Hero Section'), ('curriculum_image', 'Curriculum Approach Image'), ('assessment_intro', 'Assessment Introduction'), ('cta_section', 'Academics Call to Action'), ('admission_process', 'Admission Process'), ('requirements', 'Requirements'), ('fees', 'Fees and Tuition'), ('scholarships', 'Scholarships'), ('events_hero', 'Events Hero Section'), ('events_newsletter', 'Events Newsletter Section'), ('events_cta', 'Events Call to Action'), ('events_calendar', 'Events Calendar Placeholder'), ('news_hero', 'News Hero Section')], max_length=50),
        ),
    ]
