# Generated by Django 5.1.6 on 2025-04-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_pagecontent_page_alter_pagecontent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_email',
            field=models.EmailField(blank=True, help_text='Email for admissions inquiries', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_phone',
            field=models.CharField(blank=True, help_text='Phone for admissions inquiries', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fax_number',
            field=models.CharField(blank=True, help_text='Fax number if available', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_api_key',
            field=models.CharField(blank=True, help_text='Google Maps API key for map integration', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate for Google Maps', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate for Google Maps', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_zoom',
            field=models.PositiveSmallIntegerField(default=15, help_text='Zoom level for Google Maps (1-20)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Email for technical support', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
    ]
