# Generated by Django 5.1.6 on 2025-04-16 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_pagecontent_page_alter_pagecontent_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('teaching', 'Teaching Staff'), ('administration', 'Administration'), ('support', 'Support Staff'), ('management', 'Management'), ('other', 'Other')], max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], max_length=20)),
                ('location', models.CharField(default='On-site', max_length=100)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us'), ('academics', 'Academics'), ('admissions', 'Admissions'), ('events', 'Events'), ('news', 'News & Announcements'), ('contact', 'Contact Us'), ('staff', 'Our Staff'), ('career', 'Careers'), ('calendar', 'School Calendar'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('faq', 'FAQs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('about_preview', 'About Preview'), ('featured_programs', 'Featured Programs'), ('why_choose_us', 'Why Choose Us'), ('about_hero', 'About Hero Section'), ('mission', 'Mission Statement'), ('vision', 'Vision Statement'), ('story', 'Our Story'), ('montessori_method', 'Montessori Method'), ('values', 'Our Values'), ('academics_hero', 'Academics Hero Section'), ('curriculum_image', 'Curriculum Approach Image'), ('assessment_intro', 'Assessment Introduction'), ('cta_section', 'Academics Call to Action'), ('admission_process', 'Admission Process'), ('requirements', 'Requirements'), ('fees', 'Fees and Tuition'), ('scholarships', 'Scholarships'), ('events_hero', 'Events Hero Section'), ('events_newsletter', 'Events Newsletter Section'), ('events_cta', 'Events Call to Action'), ('events_calendar', 'Events Calendar Placeholder'), ('news_hero', 'News Hero Section'), ('contact_hero', 'Contact Hero Section'), ('staff_hero', 'Staff Hero Section'), ('career_hero', 'Career Hero Section'), ('career_intro', 'Career Introduction'), ('calendar_hero', 'Calendar Hero Section'), ('calendar_content', 'Calendar Content'), ('privacy_hero', 'Privacy Policy Hero Section'), ('privacy_content', 'Privacy Policy Content'), ('terms_hero', 'Terms of Service Hero Section'), ('terms_content', 'Terms of Service Content'), ('faq_hero', 'FAQ Hero Section')], max_length=50),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='applications/resumes/')),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='applications/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('interview', 'Selected for Interview'), ('rejected', 'Application Rejected'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('admin_feedback', models.TextField(blank=True, help_text='Feedback to be sent to the applicant')),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='website.jobposition')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-date_applied'],
            },
        ),
    ]
