# Generated by Django 5.1.6 on 2025-06-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_jobposition_alter_pagecontent_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Website icon (favicon) displayed in browser tabs. Recommended size: 32x32 or 16x16 pixels. If not provided, the school logo will be used.', null=True, upload_to='site/favicon/'),
        ),
    ]
