# Generated by Django 5.1.6 on 2025-06-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_add_favicon_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='favicon',
        ),
    ]
