# Generated by Django 5.1.6 on 2025-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_pagecontent_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('about_preview', 'About Preview'), ('featured_programs', 'Featured Programs'), ('why_choose_us', 'Why Choose Us'), ('about_hero', 'About Hero Section'), ('mission', 'Mission Statement'), ('vision', 'Vision Statement'), ('story', 'Our Story'), ('montessori_method', 'Montessori Method'), ('values', 'Our Values'), ('academics_hero', 'Academics Hero Section'), ('curriculum_approach', 'Curriculum Approach Section'), ('assessment_intro', 'Assessment Introduction'), ('cta_section', 'Academics Call to Action'), ('admission_process', 'Admission Process'), ('requirements', 'Requirements'), ('fees', 'Fees and Tuition'), ('scholarships', 'Scholarships'), ('events_hero', 'Events Hero Section'), ('events_newsletter', 'Events Newsletter Section'), ('events_cta', 'Events Call to Action'), ('events_calendar', 'Events Calendar Placeholder'), ('news_hero', 'News Hero Section'), ('contact_hero', 'Contact Hero Section'), ('staff_hero', 'Staff Hero Section'), ('career_hero', 'Career Hero Section'), ('career_intro', 'Career Introduction'), ('calendar_hero', 'Calendar Hero Section'), ('calendar_content', 'Calendar Content'), ('privacy_hero', 'Privacy Policy Hero Section'), ('privacy_content', 'Privacy Policy Content'), ('terms_hero', 'Terms of Service Hero Section'), ('terms_content', 'Terms of Service Content'), ('faq_hero', 'FAQ Hero Section')], max_length=50),
        ),
    ]
