# Generated by Django 5.1.6 on 2025-06-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_pagecontent_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for this section. Many sections already have predefined titles in the template.', max_length=200),
        ),
    ]
