# Generated by Django 5.1.6 on 2025-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_pagecontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_style',
            field=models.CharField(blank=True, choices=[('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('success', 'Success (Green)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger (Red)'), ('info', 'Info (Light Blue)'), ('light', 'Light'), ('dark', 'Dark')], default='primary', help_text='Bootstrap button style', max_length=20),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_text',
            field=models.CharField(blank=True, help_text='Text for the primary button', max_length=50),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_url',
            field=models.CharField(blank=True, help_text="URL for the primary button (can be internal like '/admissions/' or external like 'https://example.com')", max_length=200),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_style',
            field=models.CharField(blank=True, choices=[('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('success', 'Success (Green)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger (Red)'), ('info', 'Info (Light Blue)'), ('light', 'Light'), ('dark', 'Dark')], default='secondary', help_text='Bootstrap button style', max_length=20),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_text',
            field=models.CharField(blank=True, help_text='Text for the secondary button (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_url',
            field=models.CharField(blank=True, help_text='URL for the secondary button (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='show_buttons',
            field=models.BooleanField(default=False, help_text='Check to show buttons on this slide'),
        ),
    ]
