# Generated by Django 5.1.6 on 2025-06-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_heroslide_primary_button_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='primary_button_text',
            field=models.CharField(blank=True, default='Apply Now', help_text="Text for the primary button (default: 'Apply Now')", max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='primary_button_url',
            field=models.CharField(blank=True, default='/admissions/', help_text="URL for the primary button (default: '/admissions/' - can be internal like '/admissions/' or external like 'https://example.com')", max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='Contact Us', help_text="Text for the secondary button (default: 'Contact Us', leave empty to hide)", max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='/contact/', help_text="URL for the secondary button (default: '/contact/' - can be internal like '/contact/' or external like 'https://example.com')", max_length=200),
        ),
    ]
