# Generated by Django 5.1.6 on 2025-03-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='default', max_length=50)),
                ('color_scheme', models.CharField(default='blue', max_length=50)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('assignment_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('grade_notifications', models.BooleanField(default=True)),
                ('attendance_notifications', models.BooleanField(default=True)),
                ('widgets_order', models.JSONField(default=dict)),
                ('hidden_widgets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SidebarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('user_role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_role', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('size', models.CharField(default='medium', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('widget_type', models.CharField(choices=[('CALENDAR', 'Calendar'), ('ASSIGNMENTS', 'Assignments'), ('GRADES', 'Grades'), ('ATTENDANCE', 'Attendance'), ('MESSAGES', 'Messages'), ('ANNOUNCEMENTS', 'Announcements'), ('SUBJECTS', 'Subjects'), ('STUDENTS', 'Students'), ('TEACHERS', 'Teachers')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('visible_to_admin', models.BooleanField(default=True)),
                ('visible_to_teacher', models.BooleanField(default=True)),
                ('visible_to_student', models.BooleanField(default=True)),
                ('visible_to_parent', models.BooleanField(default=True)),
                ('default_position', models.PositiveIntegerField(default=0)),
                ('default_size', models.CharField(default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
