# Generated by Django 5.1.6 on 2025-04-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpreference',
            name='color_scheme',
            field=models.CharField(default='navy', max_length=50),
        ),
    ]
