# Generated by Django 5.1.6 on 2025-06-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboardpreference_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpreference',
            name='color_scheme',
            field=models.CharField(default='modern', max_length=50),
        ),
    ]
