# Generated by Django 5.1.6 on 2025-06-14 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0020_recreate_schoolsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_for_admission', models.BooleanField(default=False)),
                ('required_for_students', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=200)),
                ('child_age', models.PositiveIntegerField()),
                ('child_dob', models.DateField(blank=True, null=True)),
                ('program_of_interest', models.CharField(choices=[('toddler', 'Toddler Program'), ('primary', 'Primary Program'), ('elementary', 'Elementary Program')], max_length=20)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(help_text="Parent's message or specific questions")),
                ('how_did_you_hear', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'New Enquiry'), ('contacted', 'Contacted'), ('scheduled', 'Visit Scheduled'), ('visited', 'Visited'), ('applied', 'Application Submitted'), ('admitted', 'Admitted'), ('declined', 'Declined'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Enquiry',
                'verbose_name_plural': 'Admission Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_by_type', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('admin', 'Admin')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for approval/rejection', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentcategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.parent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.student')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Upload',
                'verbose_name_plural': 'Document Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_type', models.CharField(choices=[('parent', 'Parent'), ('prospective_parent', 'Prospective Parent'), ('vendor', 'Vendor/Supplier'), ('official', 'Government Official'), ('contractor', 'Contractor'), ('guest', 'Guest Speaker'), ('other', 'Other')], max_length=20)),
                ('company_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('purpose', models.CharField(choices=[('meeting', 'Meeting'), ('school_tour', 'School Tour'), ('pickup_dropoff', 'Pickup/Drop-off'), ('delivery', 'Delivery'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('event', 'School Event'), ('other', 'Other')], max_length=20)),
                ('purpose_description', models.TextField(blank=True, null=True)),
                ('person_to_meet', models.CharField(blank=True, max_length=200, null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('expected_duration', models.PositiveIntegerField(blank=True, help_text='Expected duration in minutes', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('id_verified', models.BooleanField(default=False)),
                ('visitor_badge_issued', models.BooleanField(default=False)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
