# Generated by Django 5.1.6 on 2025-03-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.classroom'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_subjects', to='users.student'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_subjects', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.classsubject'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.classsubject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.classsubject'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('class_subject', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('classroom', 'subject')},
        ),
    ]
