# Generated by Django 5.1.6 on 2025-03-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.IntegerField(default=0, help_text='Grade level (e.g., 1 for Grade 1)'),
        ),
    ]
