# Generated by Django 5.1.6 on 2025-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_classroom_grade_level'),
        ('users', '0011_student_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course_classrooms', to='users.student'),
        ),
    ]
