# Generated by Django 5.1.6 on 2025-04-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_youtubevideo_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content for notes', null=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Save as draft before publishing'),
        ),
    ]
