# Generated by Django 5.1.6 on 2025-06-27 21:22

import website.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursematerial_content_coursematerial_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, storage=website.storage.get_cloudinary_storage, upload_to='course_materials/'),
        ),
    ]
