# Generated by Django 5.1.6 on 2025-03-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_gradingscale_gradethreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
