# Generated by Django 5.1.6 on 2025-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_question_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (for quizzes only). When set, students will have this amount of time to complete the quiz once started.', null=True),
        ),
    ]
