# Generated by Django 5.1.6 on 2025-03-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='questions_to_display',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to randomly select from the question bank. Leave blank to show all questions.', null=True),
        ),
    ]
