# Generated by Django 5.1.6 on 2025-03-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_assignment_randomize_choices_and_more'),
        ('courses', '0005_allow_null_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='average_assignment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='average_exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='average_quiz_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='collaboration_rating',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_rating',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='independent_work_rating',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='initiative_rating',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='is_promoted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='organization_rating',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='overall_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='principal_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='promotion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='responsibility_rating',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='total_school_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReportCardSubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quiz_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('letter_grade', models.CharField(max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assignments.reportcard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
            options={
                'unique_together': {('report_card', 'subject')},
            },
        ),
    ]
