# Generated by Django 5.1.6 on 2025-03-28 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_reportcard_average_assignment_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentWeightConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('academic_term', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('classwork_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Weight percentage for classwork/assignments (e.g., 30 = 30%)', max_digits=5)),
                ('quiz_weight', models.DecimalField(decimal_places=2, default=10.0, help_text='Weight percentage for quizzes (e.g., 10 = 10%)', max_digits=5)),
                ('test_weight', models.DecimalField(decimal_places=2, default=15.0, help_text='Weight percentage for tests (e.g., 15 = 15%)', max_digits=5)),
                ('midterm_weight', models.DecimalField(decimal_places=2, default=15.0, help_text='Weight percentage for midterm exams (e.g., 15 = 15%)', max_digits=5)),
                ('project_weight', models.DecimalField(decimal_places=2, default=10.0, help_text='Weight percentage for projects (e.g., 10 = 10%)', max_digits=5)),
                ('final_exam_weight', models.DecimalField(decimal_places=2, default=20.0, help_text='Weight percentage for final exams (e.g., 20 = 20%)', max_digits=5)),
                ('include_classwork', models.BooleanField(default=True, help_text='Include classwork/assignments in final grade calculation')),
                ('include_quizzes', models.BooleanField(default=True, help_text='Include quizzes in final grade calculation')),
                ('include_tests', models.BooleanField(default=True, help_text='Include tests in final grade calculation')),
                ('include_midterm', models.BooleanField(default=True, help_text='Include midterm exams in final grade calculation')),
                ('include_projects', models.BooleanField(default=True, help_text='Include projects in final grade calculation')),
                ('include_final_exam', models.BooleanField(default=True, help_text='Include final exams in final grade calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_weight_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
