# Generated by Django 5.1.6 on 2025-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_assessmentweightconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='final_exam_weight',
        ),
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='include_classwork',
        ),
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='include_final_exam',
        ),
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='include_midterm',
        ),
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='include_projects',
        ),
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='include_quizzes',
        ),
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='include_tests',
        ),
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='quiz_weight',
        ),
        migrations.RemoveField(
            model_name='assessmentweightconfiguration',
            name='test_weight',
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='endterm_weight',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Weight percentage for end of term exams (60%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='assessmentweightconfiguration',
            name='classwork_weight',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Weight percentage for classwork (10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='assessmentweightconfiguration',
            name='midterm_weight',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Weight percentage for mid-term exams (20%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='assessmentweightconfiguration',
            name='project_weight',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Weight percentage for project work (10%)', max_digits=5),
        ),
    ]
