# Generated by Django 5.1.6 on 2025-04-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_remove_assessmentweightconfiguration_final_exam_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='attendance_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight percentage for attendance (0%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='final_exam_weight',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Weight percentage for final exams (60%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='include_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='include_classwork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='include_final_exam',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='include_midterm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='include_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='include_quizzes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='include_tests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='quiz_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight percentage for quizzes (0%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='test_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight percentage for tests (0%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='assessmentweightconfiguration',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
