# Generated by Django 5.1.6 on 2025-05-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_assessmentweightconfiguration_attendance_weight_and_more'),
        ('users', '0017_alter_customuser_role_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuizVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_versions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_versions', to='users.student')),
            ],
            options={
                'unique_together': {('student', 'assignment', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.question')),
                ('quiz_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.studentquizversion')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('quiz_version', 'question')},
            },
        ),
        migrations.CreateModel(
            name='StudentQuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.choice')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.studentquizquestion')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('quiz_question', 'choice')},
            },
        ),
        migrations.CreateModel(
            name='StudentQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.choice')),
                ('quiz_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.studentquizversion')),
            ],
            options={
                'unique_together': {('quiz_version', 'question')},
            },
        ),
    ]
