# Generated by Django 5.1.6 on 2025-05-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_studentquizversion_studentquizquestion_and_more'),
    ]

    operations = [
    ]
