# Generated by Django 5.1.6 on 2025-05-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_merge_20250515_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for categorizing questions', max_length=255, null=True),
        ),
    ]
