# Generated by Django 5.1.6 on 2025-05-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_fix_migrations'),
        ('assignments', '0016_add_tags_and_image_to_question'),
    ]

    operations = [
    ]
