# Generated by Django 5.1.6 on 2025-05-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_merge_20250515_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentquizchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentquizchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='studentquizchoice',
            name='quiz_question',
        ),
        migrations.AlterUniqueTogether(
            name='studentquizquestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentquizquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentquizquestion',
            name='quiz_version',
        ),
        migrations.AlterUniqueTogether(
            name='studentquizversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentquizversion',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='studentquizversion',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='StudentQuizAnswer',
        ),
        migrations.DeleteModel(
            name='StudentQuizChoice',
        ),
        migrations.DeleteModel(
            name='StudentQuizQuestion',
        ),
        migrations.DeleteModel(
            name='StudentQuizVersion',
        ),
    ]
