# Generated by Django 5.1.6 on 2025-05-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0019_question_image_question_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attempt_limit',
            field=models.PositiveIntegerField(default=1, help_text='Number of attempts allowed (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='randomize_choices',
            field=models.BooleanField(default=True, help_text='Whether to randomize the order of multiple choice answers.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='randomize_questions',
            field=models.BooleanField(default=True, help_text='Whether to randomize the order of questions.'),
        ),
    ]
