# Generated by Django 5.1.6 on 2025-05-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0019_add_status_to_assignment'),
        ('assignments', '0020_assignment_attempt_limit_assignment_status_and_more'),
    ]

    operations = [
    ]
