# Generated by Django 5.1.6 on 2025-04-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, help_text="If false, the slot is inactive and won't be shown to parents"),
        ),
    ]
