# Generated by Django 5.1.6 on 2025-03-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancenotification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to='users.student'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.classroom'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_taken', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='courses.classroom'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_attendance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='users.student'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('classroom', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('attendance_record', 'student')},
        ),
    ]
